"""empty message

Revision ID: 77519bab53e9
Revises: c6a0228bf87a
Create Date: 2022-09-01 22:25:37.825603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77519bab53e9'
down_revision = 'c6a0228bf87a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comentarios_fecha_registro_key', 'comentarios', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('comentarios_fecha_registro_key', 'comentarios', ['fecha_registro'])
    # ### end Alembic commands ###
